# -*- coding: utf-8 -*-
"""All changes for this project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M8QBonKgeBABa4PH5OvX10qRKTe3_Vmj
"""