# -*- coding: utf-8 -*-
"""All changes for this project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M8QBonKgeBABa4PH5OvX10qRKTe3_Vmj
"""


"""### 5 pull requests for folder structure:
1. add ReadMe File
2. add homework2_instruction folder
3. add a code_improvement folder
4. add a data folder
5. add a summary folder

### 7 pull requests for coding etiquette: 
1. improve comments for the code
2. add descriptions of question1
3. improve comments for the code
4. add descriptions of question4
5. delete unnecessary codes
6. add descriptions of question5
7. add descriptions of question2
